### PR TITLE
Revert visual fixes march

### PR DESCRIPTION
**Pull request by divyaBacancy**

### CODE REVIEW

**Review by IAmKio — APPROVED** [review]

**Review by vnovacev — COMMENTED** [review]
I think you should include changes from PR #3060 regarding xcode versioning in this PR, that PR is not needed then.
I can't comment about other changes since I'm not familiar with the code but think that much more code lines was reverted with the problematic PR.

**Comment by divyaBacancy** [comment]
> I think you should include changes from PR #3060 regarding xcode versioning in this PR, that PR is not needed then. I can't comment about other changes since I'm not familiar with the code but think that much more code lines was reverted with the problematic PR#3048

we don't need code of PR-30360
Hence we don't need that PR.

**Review by vnovacev — COMMENTED** [review]
@divyaBacancy, @IAmKio  From the DevOps perspective changes from closed PR #3060 have to be included in this PR too. We are talking about changes made by PR #3037 and #3044 and you have reverted back them with problematic PR #3048.
Also please double check other non DevOps related code (if everything will be reverted back with this PR) since we are not familiar with that.

**Comment by divyaBacancy** [comment]
@vnovacev, @IAmKio I looking two possibilities either this PR merge with master and check getting any issue or not. if facing any issue then finding issue solution(need less time for resolving) otherwise remove https://github.com/pillarwallet/pillarwallet/pull/3048 changed file from develop branch(need more time for resolving).

**Comment by vnovacev** [comment]
> @vnovacev, @IAmKio I looking two possibilities either this PR merge with master and check getting any issue or not. if facing any issue then finding issue solution(need less time for resolving) otherwise remove #3048 changed file from develop branch(need more time for resolving).

@divyaBacancy instead of merging to master and possibly make break on this branch (which state is still ok) you can trigger deploy from your separate branch, install version from AppCenter and test it out. Or another possible approach can be to try to create brand new feature branch but from master not from develop branch, and then to add all your changes again since #3048 which i suppose is not many. Then you can merge it to develop --> master. Just an ideas.

**Comment by divyaBacancy** [comment]
@vnovacev, @IAmKio We made feature branch master_list and merge into revert_visual_fixes_march. Please test review this branch https://github.com/pillarwallet/pillarwallet/tree/master_lite

**Pull request merged**
