### PR TITLE
PRO-1473 Onboarding UI

### PR DESCRIPTION
**Pull request by lalitkumarrock**
https://linear.app/pillarproject/issue/PRO-1473/pillar-wallet-onboarding

## Description

- Set new Onbording flow.
- Made new screens UI.

## How Has This Been Tested?

- Tested on Simulator 14 Pro
- Tested on Android device

## Screenshots (if appropriate):

https://github.com/pillarwallet/pillarwallet/assets/82652040/1b6038ae-79cf-4eaa-ac35-fece534be87e

https://github.com/pillarwallet/pillarwallet/assets/82652040/2d0abb0b-e6ca-483c-8afa-3b18d9c455e4

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by Yash-Chaubal — APPROVED** [review]
LGTM!

**Review by Yash-Chaubal — COMMENTED** [review]
Just a quick question, the social buttons don't do anything when I tap them - is that intended?

Also when I'm on the enable push notifications screen, clicking 'Enable' doesn't do anything - I had to press 'Skip' to continue. Couldn't record this as when I pulled up the app again, the screen was skipped when I pressed 'Import Wallet'


https://github.com/pillarwallet/pillarwallet/assets/55538608/4295eca7-dfd0-47e2-817e-3fb2cfb90bd9

**Comment by lalitkumarrock** [comment]
> Just a quick question, the social buttons don't do anything when I tap them - is that intended?
> 
> Also when I'm on the enable push notifications screen, clicking 'Enable' doesn't do anything - I had to press 'Skip' to continue. Couldn't record this as when I pulled up the app again, the screen was skipped when I pressed 'Import Wallet'
> 
>  Simulator.Screen.Recording.-.iPhone.14.Pro.-.2023-08-07.at.17.17.46.mp4

=> Social auth is pending, made new ticket for this. In Push notifications, permission is once "Enable" after the second time not have need to asked for permission.

**Comment by lalitkumarrock** [comment]
I disabled social buttons until web3Auth is implemented
simulator_screenshot_78ABF544-BA58-4CB0-9DFD-69C8654339F7

**Pull request merged**
