### PR TITLE
Release Candidate 2.32.1 (patch)

### PR DESCRIPTION
**Pull request by poocart**
Release Candidate 2.32.1

Fixes Rari estimation requests throttle.

### CODE REVIEW

**Review by mdjastrzebski — COMMENTED** [review]
It seems that the way throttling is applied there is a change when user is typing long number, we will query Rari with intermediate input and not the final one. So the estimate might not be accurate. 

This is probably small problem if input is 0,1234 (intermediate) instead of 0,12345678 (final value), but potentially a bigger issues for integer numbers: 1234 (intermediate) vs 12345678 (final value).

I do not know enough context to know if this is feasible. So just raising this to your attention.

As alternative that should avoid this problem, we could apply throttle to text input field, so that no query is done until users stops typing digits.

**Comment by jdnmr** [comment]
> It seems that the way throttling is applied there is a change when user is typing long number, we will query Rari with intermediate input and not the final one. So the estimate might not be accurate.
> 
> This is probably small problem if input is 0,1234 (intermediate) instead of 0,12345678 (final value), but potentially a bigger issues for integer numbers: 1234 (intermediate) vs 12345678 (final value).
> 
> I do not know enough context to know if this is feasible. So just raising this to your attention.
> 
> As alternative that should avoid this problem, we could apply throttle to text input field, so that no query is done until users stops typing digits.

@graszka22

**Comment by poocart** [comment]
Guys, this was updated by @mdjastrzebski with debounce for input value.

**Review by mdjastrzebski — APPROVED** [review]
LGTM ;-)

**Pull request merged**
