### PR TITLE
PRO-351 Redesign Asset Selection

### PR DESCRIPTION
**Pull request by hemadri-tank-bacancy**
Update asset selection UI.

https://user-images.githubusercontent.com/78720269/183914921-856970a6-6e1c-430c-879b-54496493e40a.mp4

### CODE REVIEW

**Comment by hemadri-tank-bacancy** [comment]
Token icon issue resolved.

https://user-images.githubusercontent.com/78720269/184297555-e2c56a4c-3f26-429c-bb20-9ce70aae2d2f.mp4

**Comment by hemadri-tank-bacancy** [comment]
Sorted From asset token list.
Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-12 at 15 07 06

**Comment by hemadri-tank-bacancy** [comment]
Center in network list.

Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-12 at 15 24 55

**Review by IAmKio — APPROVED** [review]
LGTM - great work 👍

**Pull request merged**
