### PR TITLE
PIL-1323 Customisable Banner

### PR DESCRIPTION
**Pull request by divyaBacancy**
https://user-images.githubusercontent.com/66996635/159428445-06430185-503c-4910-afd2-7c6500b554f1.mov

### CODE REVIEW

**Comment by IAmKio** [comment]
Hi @divyaBacancy,

Before i review the code, it looks like there are some design issues that need to be corrected first:

- The border radius appears to be too large
- The minimum height is too short
- The secondary text line font size looks too large
- The icon height doesn't appear to fill the banner container height enough (there is a gap at the bottom)

Screenshot 2022-03-23 at 09 42 37

Could i see an example of a banner with the background image also please? 

Thanks!

**Comment by divyaBacancy** [comment]
bannerupdated

bannerbg

**Comment by divyaBacancy** [comment]
@IAmKio Thanks for reviewing. Done with the changes.

**Comment by IAmKio** [comment]
Thanks @divyaBacancy will review the code now.

**Review by IAmKio — CHANGES_REQUESTED** [review]
Just a few changes but overall - great work!

**Comment by divyaBacancy** [comment]
@IAmKio Done with the changes.

**Review by IAmKio — APPROVED** [review]
LGTM - thanks for making the changes. @Yash-Chaubal do you mind having a look too? Cheers

**Review by Yash-Chaubal — APPROVED** [review]
All looks good to me!

**Pull request merged**
