### PR TITLE
PIL-278 BugFix/BTC Minor Bugs update

### PR DESCRIPTION
**Pull request by alazarevski**
Fixes balance shown in accounts list with bitcoinBalances in storage
Fix BTC wallet initiation with privateKey imports from the eth wallet (generate/send functions)

### CODE REVIEW

**Comment by grilix** [comment]
@alazarevski wouldn't this result in a different address being generated? :thinking:

**Comment by alazarevski** [comment]
Yes, the address will be different. Pillarwallet support mainly mnemonic as the standard is to use mnemonic. When the users import via privateKey only the privateKey is used and no mnemonic can be generated. Therefore they can derive the address just from the privateKey, and will not use mnemonic at all

**Comment by grilix** [comment]
Oh, but this should only affect generating addresses from private keys, right? :+1:

**Comment by alazarevski** [comment]
> Oh, but this should only affect generating addresses from private keys, right? 👍

Yes. Because they will only use the privateKey, the addresses will always be derived from that privateKey

**Pull request merged**
